# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pentagram', '0006_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='counter_like',
        ),
    ]
